version: "3"
services:
  ping:
    image: lab-conversa-docker
    environment:
      - DB_USER=lab
      - DB_PASSWORD=lab
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=lab
    ports:
      - 8090:8080
    networks:
      - lab
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lab
      - MYSQL_USER=lab
      - MYSQL_PASSWORD=lab
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - lab
networks:
  lab: